"""fix relationships-last2

Revision ID: 2c0d910f3cbf
Revises: beeb9bb6234d
Create Date: 2023-08-24 22:16:23.036293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0d910f3cbf'
down_revision: Union[str, None] = 'beeb9bb6234d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
